#!/bin/sh
REPO="https://github.com/caddyserver/caddy"
TAGFILTER="refs/tags"
APP="caddy"
APPBIN=$(which $APP)
APPVER="${APPBIN} version 2>&1 | grep -i "^v" | awk '{print \$1}'"

BDIR="/usr/local/bin"
GLS="git ls-remote --tags ${REPO}"
TGS="grep ${TAGFILTER}"
TFIELD="awk '{print \$2}'"
RCFILT="grep -v -e \"{}\$\" -e alpha -e beta -e \"[Rr][Cc].*\$\""
TGTRIM="sed 's/refs\/tags\///'"
TGS1="sort | uniq | tail -1"
TGS2="sort -g | uniq | tail -1"

V="${GLS} | ${TGS} | ${TFIELD} | ${RCFILT} | ${TGTRIM}"
major=$(eval "${V} | awk -F'.' '{print \$1}' | ${TGS1}")
minor=$(eval "${V} | grep ${major} | awk -F'.' '{print \$2}' | ${TGS2}")
patch=$(eval "${V} | grep ${major}.${minor} | awk -F'.' '{print \$3}' | ${TGS2}")

vers=""
[ -z "${patch}" ] && vers=$major.$minor || vers=$major.$minor.$patch
echo $vers

download() {
    echo "download $1 version"
    echo "Installing ${vers}"
    V=$(echo $vers | sed 's/v//')
    FN=${APP}_${V}_linux_amd64.tar.gz
    sudo rm -f /tmp/${FN}
    wget -qc ${REPO}/releases/download/${vers}/${FN} -O /tmp/${FN}
    sudo rm -f ${BDIR}/${APP}
    sudo mkdir /tmp/${APP}_${V}
    sudo tar axf /tmp/${FN} -C /tmp/${APP}_${V}
    sudo install /tmp/${APP}_${V}/${APP} ${BDIR}
    sudo rm -f /tmp/${FN}
    sudo rm -rf /tmp/${APP}_${V}
}

uptodate() {
    echo $APP" version is current"
}

if [ -z "${APPBIN}" ]; then
    echo "Not Installed"
    download new
else
    echo "Installed"
    APPMAJOR=$(eval $APPVER | awk -F'.' '{print $1}')
    APPMINOR=$(eval $APPVER | awk -F'.' '{print $2}')
    APPPATCH=$(eval $APPVER | awk -F'.' '{print $3}')
    if [ $((${APPMAJOR})) -lt $((${major})) ]; then
        download major
    else
        if [ $((${APPMINOR})) -lt $((${minor})) ]; then
            download minor
        else
            if [ $((${APPPATCH})) -lt $((${patch})) ]; then
                download patch
            else
                uptodate
            fi
        fi
    fi
fi
