#!/bin/sh
REPO="https://github.com/docker/compose"
TAGFILTER="refs/tags"
APP="docker-compose"
APPBIN=$(which ${APP})
APPVER="${APP} --version | awk '{print \$3}' | sed 's/,//'"

BDIR="/usr/local/bin"
GLS="git ls-remote --tags ${REPO}"
TGS="grep ${TAGFILTER}"
TFIELD="awk '{print \$2}'"
RCFILT="grep -v -e \"{}\$\" -e alpha -e beta -e \"[Rr][Cc].*\$\" -e \"/v\" -e \"/docs\""
TGTRIM="sed 's/refs\/tags\///'"
TGS1="sort | uniq | tail -1"
TGS2="sort -g | uniq | tail -1"

V="${GLS} | ${TGS} | ${TFIELD} | ${RCFILT} | ${TGTRIM}"
major=$(eval "${V} | awk -F'.' '{print \$1}' | ${TGS1}")
minor=$(eval "${V} | grep ${major} | awk -F'.' '{print \$2}' | ${TGS2}")
patch=$(eval "${V} | grep ${major}.${minor} | awk -F'.' '{print \$3}' | ${TGS2}")

vers=""
[ -z "${patch}" ] && vers=$major.$minor || vers=$major.$minor.$patch
echo $vers

OS=$(uname -s)
ARCH=$(uname -m)

download() {
    echo "download $1 version"
    echo "Installing ${vers}"
    sudo curl -L "${REPO}/releases/download/${vers}/${APP}-${OS}-${ARCH}" -o /usr/local/bin/${APP}
    sudo chmod +x ${BDIR}/${APP}
}

uptodate() {
    echo ${APP} "version is current"
}

if [ -z "${APPBIN}" ]; then
    echo "Not Installed"
    download new
else
    APPMAJOR=$(eval $APPVER | awk -F'.' '{print $1}')
    APPMINOR=$(eval $APPVER | awk -F'.' '{print $2}')
    APPPATCH=$(eval $APPVER | awk -F'.' '{print $3}')
    if [ $((${APPMAJOR})) -lt $((${major})) ]; then
        download major
    else
        if [ $((${APPMINOR})) -lt $((${minor})) ]; then
            download minor
        else
            if [ $((${APPPATCH})) -lt $((${patch})) ]; then
                download patch
            else
                uptodate
            fi
        fi
    fi
fi
