#!/bin/bash
R="https://github.com/containous"
P="traefik"
GR=${R}/${P}

revs=$( git ls-remote --tags ${GR} | grep refs/tags/ | grep -v -e beta -e rc[123456789] -e '{' -e '}'| awk '{print $2}' | sed "s/refs\/tags\/v//")

major=0
minor=0
patch=0
for r in $revs
do
    mj=$(echo $r | awk -F'.' '{print $1}')
    if [ $major -lt $((mj)) ]; then
        major=$mj
    fi
done

for r in $revs
do
    mj=$(echo $r | awk -F'.' '{print $1}')
    mi=$(echo $r | awk -F'.' '{print $2}')
    if [ $major -eq $((mj)) ]; then
        if [ $minor -lt $((mi)) ]; then
            minor=$mi
        fi
    fi
done

for r in $revs
do
    mj=$(echo $r | awk -F'.' '{print $1}')
    mi=$(echo $r | awk -F'.' '{print $2}')
    pt=$(echo $r | awk -F'.' '{print $3}')
    if [ $major -eq $((mj)) ]; then
        if [ $minor -eq $((mi)) ]; then
            if [ $patch -lt $((pt)) ]; then
                patch=$pt
            fi
        fi
    fi
done

vers=""

if [ "$patch" = "" ]; then
    vers=$major.$minor
else
    vers=$major.$minor.$patch
fi

echo $vers
url=${GR}/releases/download/v${vers}/${P}_v${vers}_linux_amd64.tar.gz
echo ${url}
sudo rm -rf /tmp/${P}*
wget -O /tmp/${P}.tar.gz ${url}
tar axf /tmp/${P}.tar.gz -C /tmp
sudo cp /tmp/${P} /usr/local/bin/${P}
sudo chmod +x /usr/local/bin/${P}
sudo rm -rf /tmp/${P}*
